definitions:
  models.User:
    properties:
      eid:
        type: string
      status:
        type: string
      uid:
        type: integer
    type: object
info:
  contact: {}
paths:
  /api/user/{uid}:
    get:
      parameters:
      - description: User UID
        in: path
        name: uid
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
      summary: Find User by UID
      tags:
      - User
swagger: "2.0"
